### ISSUE TITLE
TypeError：Cannot read property ‘product’ of undefined

### ISSUE THREAD

**Issue by PRSJMC** [adams549659584/edu-refurbished-surface-monitor#1]
![image](https://user-images.githubusercontent.com/46528990/162183366-e0f7c2c2-ff67-4816-967d-6b1cd6171e8c.png)

Adams你好，打扰了，报错如上图，是不是微软网页变了？

**Comment by adams549659584** [comment]
看了下，微软接口响应的结构变了，暂时不能用了
